---
title: "Calculate Speed and Delay"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculate Speed and Delay}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(tc.sensors)
library(parallel)
library(purrr)
library(doParallel)
library(foreach)
library(dplyr)
library(magrittr)
library(tictoc) 
```

## Aggregate hourly speed  

First, we will pull the data for three random sensors from January 1 to January 15, 2019. 

```{r}
sensor_config <- pull_configuration() %>% 
  dplyr::filter(detector_abandoned != F) %>% 
  dplyr::sample_n(1)

cores <- detectCores()
cl <- makeCluster(cores)
registerDoParallel(cl)
tic() # Start the timer


sensor_data <-
  foreach(j = sensor_config$detector_name) %dopar% {
  date_range <- seq(as.Date("2019/03/01"), as.Date("2019/03/31"), by = "days")
  n <- length(date_range)
  loops_ls <- vector("list", n)
  
  for (i in 1:n) {
    loops_ls[[i]] <- tc.sensors::pull_sensor(j, date_range[[i]])
  }
  
  loops_df <- data.table::rbindlist(loops_ls)
}

toc()
stopCluster(cl)

```

Do some data cleaning.  

```{r}
clean_sensor_data <- purrr::map(sensor_data, replace_impossible, interval_length = NA) %>% # replace 
  purrr::map(scrub_sensor, interval_length = NA)
```


```{r}
agg_hour <- purrr::map(clean_sensor_data, aggregate_sensor_data,
                       config = sensor_config,
                       interval_length = 1) %>% 
  purrr::map(add_day_type) %>% 
  purrr::map(add_weather)
  

agg_period <- aggregate_sensor_data(clean_sensor_data[[1]], config = sensor_config,
                                    interval_length = 6) %>% 
  add_day_type() %>% 
  add_weather(save_raw = FALSE,
              interval_length = 6)

```

