name: check-package

on:
   push:
     branches:
       - master
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: rocker/geospatial
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-${{ '3.6' }}-${{ hashFiles('DESCRIPTION') }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update && apt-get install -y --no-install-recommends \
          libxml2-dev \
          libssl-dev \
          libpng-dev \
          libudunits2-dev \
          libcurl4-openssl-dev
          sudo apt autoremove -y
      - name: Install Package Dependencies
        run: |-
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'never', repos = 'https://mirror.las.iastate.edu/CRAN/')"
      - name: Check Package
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
